import operator
from typing import Annotated, Sequence, TypedDict
from langchain_core.messages import BaseMessage

class ResearchState(TypedDict):
    """
    The state of the LangGraph Research Agent. 
    This dictionary is passed around between nodes during execution.
    """
    # The original topic the user asked to research
    topic: str
    
    # The history of messages (what the LLM generated, what tools were called, the tool results)
    # Annotated with operator.add means new messages are appended to the list, not overwritten.
    messages: Annotated[Sequence[BaseMessage], operator.add]
    
    # Internal counter to prevent infinite research loops
    loop_count: int
    
    # The final research report generated by the writer
    final_report: str
