# InsureDoc: CosmosDB & AI Search with Private Link Architecture
# ---------------------------------------------------------------------------------------
# VALUE: This is the 'Persistence' layer. By using Private Link, we ensure 
# your dental claim records and policy vectors are unreachable via the web.
# ---------------------------------------------------------------------------------------

# COSMOSDB: This stores the 'Stuck' claim states the AI reads.
# Kind 'MongoDB' is used to mimic the document-store logic of GOLD-AI-API.
resource "azurerm_cosmosdb_account" "main" {
  name                = "cosmos-insuredoc-${var.suffix}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  capabilities { name = "EnableMongo" }
  
  consistency_policy {
    consistency_level = "Eventual" # Simplest consistency, least demand on zonal capacity
  }

  geo_location {
    location          = azurerm_resource_group.main.location
    failover_priority = 0
  }

  # FIREWALL: Only allow traffic from within the Virtual Network filter.
  is_virtual_network_filter_enabled = true
}

# AI SEARCH: This is the 'Knowledge Base'. It stores the embeddings and 
# text chunks generated by the Ingestion microservice.
resource "azurerm_search_service" "main" {
  name                = "srch-insuredoc-${var.suffix}"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  sku                 = "basic" # Entry level with vector support
}

# PRIVATE ENDPOINT: This creates the private IP for CosmosDB in the VNet.
resource "azurerm_private_endpoint" "cosmos" {
  name                = "pe-cosmos-insuredoc"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  subnet_id           = azurerm_subnet.endpoints.id

  private_service_connection {
    name                           = "cosmos-connection"
    private_connection_resource_id = azurerm_cosmosdb_account.main.id
    is_manual_connection           = false
    subresource_names              = ["MongoDB"]
  }

  private_dns_zone_group {
    name                 = "cosmos-dns-group"
    private_dns_zone_ids = [azurerm_private_dns_zone.cosmos.id]
  }
}
