nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

env: {}
secretEnv: []

ingress:
  enabled: false
  className: webapprouting.kubernetes.azure.com
  annotations: {}
  host: chart-example.local
  path: /
  pathType: Prefix
  tls:
    enabled: false
    secretName: app-tls

keyVault:
  enabled: false
  name: ""
  tenantId: ""
  useVMManagedIdentity: true
  userAssignedIdentityID: ""
  mountPath: /mnt/secrets-store
  secrets: []

resources: {}

livenessProbe:
  path: /health
  initialDelaySeconds: 20
  periodSeconds: 15

readinessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
