version: '3.8'

services:
  # LOCAL MONGODB
  mongodb:
    image: mongo:latest
    container_name: insuredoc-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # LOCAL QDRANT
  qdrant:
    image: qdrant/qdrant:latest
    container_name: insuredoc-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  # INGESTION SERVICE
  ingestion-service:
    build: 
      context: .
      dockerfile: ./ingestion-service/Dockerfile
    container_name: insuredoc-ingestion
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      - qdrant
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev:ingestion

  # CLAIM SERVICE
  claim-service:
    build:
      context: .
      dockerfile: ./claim-service/Dockerfile
    container_name: insuredoc-claim-service
    ports:
      - "3002:3002"
    env_file: .env
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev:claim

  # ORCHESTRATOR SERVICE
  orchestrator-service:
    build:
      context: .
      dockerfile: ./orchestrator-service/Dockerfile
    container_name: insuredoc-orchestrator
    ports:
      - "3003:3003"
    env_file: .env
    depends_on:
      - ingestion-service
      - claim-service
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev:orchestrator

  # FRONTEND SERVICE
  frontend-service:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    container_name: insuredoc-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-service:/app
      - /app/node_modules
    depends_on:
      - orchestrator-service

volumes:
  mongodb_data:
  qdrant_data:
