apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-api-service.fullname" . }}
  labels:
    {{- include "k8s-api-service.labels" . | nindent 4 }}
data:
  APP_ENV_VAR: {{ .Values.env.APP_ENV_VAR | quote }}
