apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-api-service.fullname" . }}
  labels:
    {{- include "k8s-api-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8s-api-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-api-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_ENV_VAR
              valueFrom:
                configMapKeyRef:
                  name: {{ include "k8s-api-service.fullname" . }}
                  key: APP_ENV_VAR
            {{- range .Values.keyvault.secrets }}
            - name: {{ .key | default .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s-api-service.fullname" $ }}-kv-sync
                  key: {{ .key | default .name }}
            {{- end }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "k8s-api-service.fullname" . }}-kv
