{{- if .Values.keyvault.name }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "k8s-api-service.fullname" . }}-kv
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "k8s-api-service.fullname" . }}-kv-sync
      type: Opaque
      data:
        {{- range .Values.keyvault.secrets }}
        - objectName: {{ .name }}
          key: {{ .key | default .name }}
        {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyvault.clientID | default "" }}
    keyvaultName: {{ .Values.keyvault.name }}
    objects: |
      array:
        {{- range .Values.keyvault.secrets }}
        - |
          objectName: {{ .name }}
          objectType: secret
          objectVersion: ""
        {{- end }}
    tenantId: {{ .Values.keyvault.tenantId }}
{{- end }}
